In [4]:
import pandas as pd

df = pd.read_csv(
    "../data/interim/all_projects_extracted1.csv",
    
)

df = df.drop(df.index[0]).reset_index(drop=True)

df.head(10)

,0,1,2,3,4,5,6,7,8,9
0,NaN,Sl.No,STATE NAME,Allocated To,Sector,Project Count,Original Cost\n(Latest Revised Cost)\nin Rs. C...,Cumulative\nExpenditure\nin Rs. Crore,NaN,NaN
1,NaN,1,Offshore,Ministry of Petroleum & Natural Gas,Oil & Gas,7,25889.58\n29147.7,16132.96,NaN,NaN
2,NaN,NaN,NaN,Ministry of Railways,Railways,1,819\n819,580.51,NaN,NaN
3,NaN,NaN,PAN India,Department of Telecommunications,Telecommunication,5,141080.68\n263402,73544.16,NaN,NaN
4,NaN,NaN,NaN,Ministry of Railways,Railways,1,274.39\n274.39,0.00,NaN,NaN
5,NaN,NaN,NaN,NaN,Total,14,168063.65,90257.63,NaN,NaN
6,NaN,2,Andaman & Nicobar,Ministry of Housing & Urban Affairs,Real Estate,1,209.88\n209.88,0.00,NaN,NaN
7,NaN,NaN,NaN,Ministry of Road Transport & Highways,Roads & Highways,3,653.97\n1081.48,0.00,NaN,NaN
8,NaN,NaN,NaN,NaN,Total,4,863.85,0.00,NaN,NaN
9,NaN,3,Andhra Pradesh,Department for Promotion of Industry & \nInter...,Real Estate,3,7061.44\n7061.44,966.01,NaN,NaN

In [5]:
df.columns = df.iloc[0]
df = df.iloc[1:].reset_index(drop=True)
df.head(10)

,NaN,Sl.No,STATE NAME,Allocated To,Sector,Project Count,Original Cost\n(Latest Revised Cost)\nin Rs. Crore,Cumulative\nExpenditure\nin Rs. Crore,NaN,NaN
0,NaN,1,Offshore,Ministry of Petroleum & Natural Gas,Oil & Gas,7,25889.58\n29147.7,16132.96,NaN,NaN
1,NaN,NaN,NaN,Ministry of Railways,Railways,1,819\n819,580.51,NaN,NaN
2,NaN,NaN,PAN India,Department of Telecommunications,Telecommunication,5,141080.68\n263402,73544.16,NaN,NaN
3,NaN,NaN,NaN,Ministry of Railways,Railways,1,274.39\n274.39,0.00,NaN,NaN
4,NaN,NaN,NaN,NaN,Total,14,168063.65,90257.63,NaN,NaN
5,NaN,2,Andaman & Nicobar,Ministry of Housing & Urban Affairs,Real Estate,1,209.88\n209.88,0.00,NaN,NaN
6,NaN,NaN,NaN,Ministry of Road Transport & Highways,Roads & Highways,3,653.97\n1081.48,0.00,NaN,NaN
7,NaN,NaN,NaN,NaN,Total,4,863.85,0.00,NaN,NaN
8,NaN,3,Andhra Pradesh,Department for Promotion of Industry & \nInter...,Real Estate,3,7061.44\n7061.44,966.01,NaN,NaN
9,NaN,NaN,NaN,Department of Higher Education,Education,1,305\n305,64.25,NaN,NaN

In [7]:
df.sample(10)

,NaN,Sl.No,STATE NAME,Allocated To,Sector,Project Count,Original Cost\n(Latest Revised Cost)\nin Rs. Crore,Cumulative\nExpenditure\nin Rs. Crore,NaN,NaN
1658,NaN,682,"New line Dahod-Indore via Sardarpur, Jabuwa an...","Multi-States \n(Gujarat, Madhya \nPradesh)",06/2012\n(06/2012),02/2027\n(02/2027),456.07\n(3516.77),4157.76,55,NaN
1544,NaN,583,4th LINE BETWEEN BAREJADI NANDEJ-SANAND-AHMEDA...,Gujarat,02/2023\n(02/2023),03/2027\n(07/2028),961.67\n(961.67),507.6,21,NaN
922,NaN,94,KOLGAON EXPANSION DEEP OC MINE\n(Western Coalf...,Maharashtra,01/2023\n(09/2023),03/2027\n(-),198.71\n(198.71),23.54,2.82,NaN
2629,NaN,1511,Construction of Greenfield Connectivity to Jew...,"Multi-States \n(Haryana, Uttar \nPradesh)",07/2022\n(06/2023),06/2025\n(04/2027),2920.69\n(3485.77),1024.9,69.77,NaN
215,NaN,NaN,NaN,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,1,499\n499,201.99,NaN,NaN
436,NaN,14,Bulk Loading Hub- Kanpur\n(MinistryofPetroleum...,Uttar Pradesh,09/2025\n(09/2025),09/2027\n(09/2027),186\n(186),NaN,NaN,NaN
2759,NaN,1623,4L of Greenfield section from Sirhind to Moha...,Punjab,03/2022\n(05/2023),05/2025\n(06/2026),1237.65\n(1301.15),979.97,88.82,NaN
1353,NaN,439,2G Ethanol Biorefinery at Bathinda\n(Hindustan...,Punjab,05/2020\n(05/2020),02/2023\n(12/2026),1421.46\n(1421.46),1263.61,95.8,NaN
1970,NaN,950,Estimate for Improvement to two lane with pave...,Bihar,01/2022\n(10/2024),04/2026\n(04/2027),495.16\n(495.16),0,33,NaN
3068,NaN,1887,Improvement/construction of 2-lane with paved ...,Uttarakhand,05/2022\n(11/2024),11/2026\n(11/2026),649.6\n(649.6),0,29.72,NaN